# Generated by Django 6.0 on 2025-12-20 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, help_text='mobile, tablet, desktop', max_length=50, verbose_name='Cihaz Tipi')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Tarayıcı')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='İşletim Sistemi')),
                ('location', models.CharField(blank=True, help_text='GeoIP ile tespit edilen konum', max_length=200, verbose_name='Konum')),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='Giriş Zamanı')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='Çıkış Zamanı')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Son Aktivite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_log', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Oturumu',
                'verbose_name_plural': 'Kullanıcı Oturumları',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Kullanıcı silinse bile kayıt kalır', max_length=150, verbose_name='Kullanıcı Adı')),
                ('action', models.CharField(choices=[('CREATE', 'Oluşturma'), ('UPDATE', 'Güncelleme'), ('DELETE', 'Silme'), ('VIEW', 'Görüntüleme'), ('LOGIN', 'Giriş'), ('LOGOUT', 'Çıkış'), ('LOGIN_FAILED', 'Başarısız Giriş'), ('EXPORT', 'Dışa Aktarma'), ('IMPORT', 'İçe Aktarma'), ('PERMISSION_CHANGE', 'Yetki Değişikliği'), ('PASSWORD_CHANGE', 'Şifre Değişikliği'), ('PASSWORD_RESET', 'Şifre Sıfırlama'), ('API_CALL', 'API Çağrısı'), ('CUSTOM', 'Özel')], db_index=True, default='CUSTOM', max_length=50, verbose_name='İşlem')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Obje ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Obje Gösterimi')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": {"old": "...", "new": "..."}}', verbose_name='Değişiklikler')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Ek Veriler')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma Tarihi')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='İçerik Tipi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=255, verbose_name='Obje ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Obje Gösterimi')),
                ('change_type', models.CharField(choices=[('CREATE', 'Oluşturma'), ('UPDATE', 'Güncelleme'), ('DELETE', 'Silme')], max_length=10, verbose_name='Değişiklik Tipi')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Alan Adı')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Eski Değer')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Yeni Değer')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Tüm Değişiklikler')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Değişiklik Zamanı')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_changes', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Model Değişiklik Logu',
                'verbose_name_plural': 'Model Değişiklik Logları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'created_at'], name='audit_model_content_674d58_idx')],
            },
        ),
    ]
