# Generated by Django 6.0 on 2025-12-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetricSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Tarih')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='Toplam Request')),
                ('successful_requests', models.PositiveIntegerField(default=0, verbose_name='Başarılı (2xx)')),
                ('client_errors', models.PositiveIntegerField(default=0, verbose_name='Client Error (4xx)')),
                ('server_errors', models.PositiveIntegerField(default=0, verbose_name='Server Error (5xx)')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='Ortalama Response Time (ms)')),
                ('max_response_time', models.FloatField(default=0, verbose_name='Max Response Time (ms)')),
                ('min_response_time', models.FloatField(default=0, verbose_name='Min Response Time (ms)')),
                ('p95_response_time', models.FloatField(default=0, verbose_name='P95 Response Time (ms)')),
                ('unique_users', models.PositiveIntegerField(default=0, verbose_name='Unique Users')),
                ('unique_ips', models.PositiveIntegerField(default=0, verbose_name='Unique IPs')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
            ],
            options={
                'verbose_name': 'Günlük Metrik Özeti',
                'verbose_name_plural': 'Günlük Metrik Özetleri',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EndpointMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Tarih')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Path')),
                ('method', models.CharField(max_length=10, verbose_name='Method')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='Request Sayısı')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Hata Sayısı')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='Ortalama Response Time (ms)')),
                ('max_response_time', models.FloatField(default=0, verbose_name='Max Response Time (ms)')),
            ],
            options={
                'verbose_name': 'Endpoint Metriği',
                'verbose_name_plural': 'Endpoint Metrikleri',
                'ordering': ['-date', '-request_count'],
                'unique_together': {('date', 'path', 'method')},
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zaman')),
                ('level', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='ERROR', max_length=10, verbose_name='Seviye')),
                ('logger_name', models.CharField(blank=True, max_length=200, verbose_name='Logger')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('exception_type', models.CharField(blank=True, max_length=200, verbose_name='Exception Tipi')),
                ('exception_message', models.TextField(blank=True, verbose_name='Exception Mesajı')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Path')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Method')),
                ('user_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='User ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('occurrence_count', models.PositiveIntegerField(default=1, verbose_name='Tekrar Sayısı')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Son Görülme')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Çözüldü')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözülme Zamanı')),
                ('resolved_by', models.CharField(blank=True, max_length=150, verbose_name='Çözen')),
            ],
            options={
                'verbose_name': 'Hata Logu',
                'verbose_name_plural': 'Hata Logları',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', 'timestamp'], name='log_analyti_level_3ff6be_idx'), models.Index(fields=['exception_type', 'timestamp'], name='log_analyti_excepti_5aa028_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zaman')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Path')),
                ('method', models.CharField(max_length=10, verbose_name='Method')),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, verbose_name='Status Code')),
                ('response_time', models.FloatField(verbose_name='Response Time (ms)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Request Metriği',
                'verbose_name_plural': 'Request Metrikleri',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'status_code'], name='log_analyti_timesta_ad1654_idx'), models.Index(fields=['path', 'timestamp'], name='log_analyti_path_c94f83_idx')],
            },
        ),
    ]
